{{- $values := index $.Values "netconf" -}}
{{- if ($values.exitEditConfig).config -}}
{{- include
      "accelleran.common.job"
      (fromYaml (include "accelleran.cell-wrapper.netconf.exit.job.args" .))
-}}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.exit.job.args" -}}
{{- $ := . -}}
{{- $values := index $.Values "netconf" -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{
    (mergeOverwrite
      (deepCopy $values)
      (dict "annotations" (dict
        "helm.sh/hook" "pre-delete,pre-upgrade,pre-rollback"
        "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded"
      ))
    ) | toYaml | nindent 2
  }}

name: "{{ .Release.Name }}-netconf-exit-config"
backoffLimit: 2

volumes:
  - name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-exit-rpcs
    configMap:
      name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-exit-rpcs
      defaultMode: 0777

initContainers:
  - {{ fromYaml (include "accelleran.cell-wrapper.netconf.wait.container" .) | toYaml | nindent 4 }}

containers:
  - {{ fromYaml (include "accelleran.cell-wrapper.netconf.exit.container" .) | toYaml | nindent 4 }}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.exit.container" -}}
{{- $ := . -}}
{{- $values := $.Values.netconf -}}
{{- include
      "accelleran.common.container"
      (fromYaml (include "accelleran.cell-wrapper.netconf.exit.container.args" $))
-}}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.exit.container.args" -}}
{{- $ := . -}}
{{- $values := $.Values.netconf -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ (mergeOverwrite (deepCopy $values) (fromYaml (include "accelleran.cell-wrapper.netconf.exit.container.valueOverrides" .))) | toYaml | nindent 2 }}

envFrom:
  - secretRef:
      name: {{ include "accelleran.cell-wrapper.netconf.secret.authentication.name" $ }}

volumeMounts:
  - name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-exit-rpcs
    mountPath: /rpcs
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.exit.container.valueOverrides" -}}
{{- $ := . -}}
{{- $values := $.Values.netconf -}}
containerName: netconf-exit-config
args:
  - "--host"
  - {{ include "accelleran.cell-wrapper.netconf.service.name" $ | quote }}
  - "--port"
  - {{ ((($values.service).ports).netconf).port | default 8300 | quote }}
  - "--user"
  - "$(username)"
  - "--pass"
  - "$(password)"
  {{- range $index, $configRpc := $values.exitEditConfig.config }}
  {{- $configRpc = tpl $configRpc $ -}}
  {{- if $configRpc }}
  - "--edit"
  - "/rpcs/exit-edit-config-{{- $index -}}.xml"
  {{- end }}
  {{- end }}
{{- end -}}
