global:

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  nodeSelector: {}


# Number of supported components
#   Description:  You have to specify the amount of different components that should be supported.
#                 Therefore, you have to specify:
#                 - the number of AMFs that will be used
#                 - the number of CU-UPs that will be used
#                 - the number of DUs that will be used
#                 - the number of CELLSs that will be used
#                   i.e. DU1 supporting 3 cells and DU2 supported 2 cells => numOfCells: 5
#                 - the number of UEs that will be used
numOfAmfs: 1
numOfCuUps: 1
numOfDus: 3
numOfCells: 3
numOfUes: 16

bootstrap:
  create: true
  configMapName: ""

  # CU-CP Instance ID
  #   Description:  The Instance ID of the CU-CP component that
  #                 will be used in the bootstrap file.
  #                 The Instance ID must consist of lower case alphanumeric characters
  #                 or '-', start with an alphabetic character, and end with an alphanumeric
  #                 character (e.g. 'my-name',  or 'abc-123', regex used for validation is
  #                 '^[a-z0-9-]+$'). The Instance ID also cannot be longer than 19 characters!
  #
  #   Example:
  # instanceId: "cucp-1"
  #
  instanceId: "cucp-1"

  redis:
    enabled: true
    hostname: ""
    port: 0

  nats:
    enabled: true
    hostname: ""
    port: 0

drax:
  technology: "5g"
  role: "5g"


cu-cp:
  enabled: true
  
  nameOverride: "cu-cp"
  fullnameOverride: ""

  initImage:
    redis:
      repository: accelleran/acc-generic-img
      tag: "0.8.0-dev.2"
      pullPolicy: IfNotPresent
    nats:
      repository: accelleran/acc-generic-img
      tag: "0.8.0-dev.2"
      pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


netconf:
  enabled: true

  nameOverride: "netconf"
  fullnameOverride: ""

  containerName: "netconf"

  image:
    repository: accelleran/cucp-netconf
    tag: ""
    pullPolicy: IfNotPresent

  readinessProbe:
    exec:
      command:
        - "test"
        - "-f"
        - "ready"
    initialDelaySeconds: 15
    periodSeconds: 30

  service:
    enabled: true
    name: ""
    type: "ClusterIP"
    ports:
      netconf:
        protocol: "TCP"
        port: 8300
        targetPort: null
        nodePort: null


gnb-controller:
  enabled: true

  nameOverride: "gnb-controller"
  fullnameOverride: ""

  containerName: "gnb-controller"

  image:
    repository: accelleran/gnbcontrollerappl
    tag: ""
    pullPolicy: IfNotPresent


amf-controller:
  enabled: true

  nameOverride: "amf-controller"
  fullnameOverride: ""

  containerName: "amf-controller"

  image:
    repository: accelleran/amfcontrollerappl
    tag: ""
    pullPolicy: IfNotPresent


cu-up-controller:
  enabled: true

  nameOverride: "cu-up-controller"
  fullnameOverride: ""

  containerName: "cu-up-controller"

  image:
    repository: accelleran/cuupcontrollerappl
    tag: ""
    pullPolicy: IfNotPresent


du-controller:
  enabled: true

  nameOverride: "du-controller"
  fullnameOverride: ""

  containerName: "du-controller"

  image:
    repository: accelleran/ducontrollerappl
    tag: ""
    pullPolicy: IfNotPresent


pm-controller:
  enabled: true

  nameOverride: "pm-controller"
  fullnameOverride: ""

  containerName: "pm-controller"

  image:
    repository: accelleran/pmcontrollerappl
    tag: ""
    pullPolicy: IfNotPresent


res-mgr:
  enabled: true

  nameOverride: "res-mgr"
  fullnameOverride: ""

  containerName: "res-mgr"

  image:
    repository: accelleran/resmgrappl
    tag: ""
    pullPolicy: IfNotPresent


sctp-ng:
  enabled: true

  nameOverride: "sctp-ng"
  fullnameOverride: ""

  containerName: "sctp-ng"

  image:
    repository: accelleran/sctpcpngappl
    tag: ""
    pullPolicy: IfNotPresent


sctp-e1:
  enabled: true

  nameOverride: "sctp-e1"
  fullnameOverride: ""

  containerName: "sctp-e1"

  image:
    repository: accelleran/sctpcpe1appl
    tag: ""
    pullPolicy: IfNotPresent

  service:
    enabled: true
    name: ""
    type: "LoadBalancer"
    ports:
      e1ap:
        appProtocol: "e1-interface"
        protocol: "SCTP"
        port: 38462
        targetPort: 0
        nodePort: 0
    loadBalancerIP: ""
    externalTrafficPolicy: "Local"


sctp-f1:
  enabled: true

  nameOverride: "sctp-f1"
  fullnameOverride: ""

  containerName: "sctp-f1"

  image:
    repository: accelleran/sctpcpf1appl
    tag: ""
    pullPolicy: IfNotPresent

  service:
    enabled: true
    name: ""
    type: "LoadBalancer"
    ports:
      f1ap:
        appProtocol: "f1-control"
        protocol: "SCTP"
        port: 38472
        targetPort: 0
        nodePort: 0
    loadBalancerIP: ""
    externalTrafficPolicy: "Local"


ng-ap:
  enabled: true

  nameOverride: "ng-ap"
  fullnameOverride: ""

  containerName: "ng-ap"

  replicaCount: null

  image:
    repository: accelleran/ngapappl
    tag: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


e1-cp:
  enabled: true

  nameOverride: "e1-cp"
  fullnameOverride: ""

  containerName: "e1-cp"

  replicaCount: null

  image:
    repository: accelleran/e1cpappl
    tag: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


f1-ap:
  enabled: true

  nameOverride: "f1-ap"
  fullnameOverride: ""

  containerName: "f1-ap"

  replicaCount: null

  image:
    repository: accelleran/f1apintfappl
    tag: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


rr-ctrl:
  enabled: true

  nameOverride: "rr-ctrl"
  fullnameOverride: ""

  containerName: "rr-ctrl"

  replicaCount: null

  image:
    repository: accelleran/rrctrlappl
    tag: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


ds-ctrl:
  enabled: true

  nameOverride: "ds-ctrl"
  fullnameOverride: ""

  containerName: "ds-ctrl"

  replicaCount: null

  initImage:
    repository: accelleran/acc-generic-img
    tag: "0.8.0-dev.2"
    pullPolicy: IfNotPresent

  image:
    repository: accelleran/dsctrlappl
    tag: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  autoscaling:
    enabled: false
    factorReplicas: 8

  nodeSelector: {}

  tolerations: []

  affinity: {}

nats:
  enabled: true

  natsBox:
    enabled: false

redis:
  enabled: true

  architecture: standalone
  auth:
    enabled: false
