apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accelleran.service-monitor.fullname" . }}
  labels:
    {{- include "accelleran.service-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "accelleran.service-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "accelleran.service-monitor.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "accelleran.service-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if eq (tpl .Values.accelleranLicense.enabled .) "true" }}
          image: "{{ .Values.image.repository }}-license:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{ end }}        
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONITORED_NAMESPACES
              value: "{{ tpl .Values.monitoredNamespaces . }}"
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:      
            {{ if eq (tpl .Values.accelleranLicense.enabled .) "true" }}
            - mountPath: "/etc/license/license.crt"
              subPath: "license.crt"
              name: accelleran-license
              readOnly: true
            {{ end }}
          command: ["/app/main"]
          #livenessProbe:
          #  httpGet:
          #    path: /services
          #    port: {{ .Values.service.port }}
          #readinessProbe:
          #  httpGet:
          #    path: /services
          #    port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{ if eq (tpl .Values.accelleranLicense.enabled .) "true" }}
        - name: accelleran-license
          secret:
            secretName: {{ tpl .Values.accelleranLicense.licenseSecretName . }}
        {{ end }}
