apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  labels:
    {{- include "accelleran.service-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 8080
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "accelleran.service-monitor.selectorLabels" . | nindent 4 }}
