apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 3.0.3
# renovate: image=accelleran/cw-netconf versioning=loose extract_version=^CW(?<version>.*)$
appVersion: "CW3.0.3"
dependencies:
  - name: common
    version: 0.2.0
    repository: https://accelleran.github.io/helm-charts-ng/
  - name: nats
    condition: nats.enabled
    version: 1.1.9
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 18.16.0
    repository: https://charts.bitnami.com/bitnami/
