global:

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  nodeSelector: {}

# Number of supported components
#   Description:  You have to specify the amount of different components that should be supported.
#                 Therefore, you have to specify:
#                 - the number of E2 nodes that will be used
numOfE2Nodes: 2

bootstrap:
  create: true
  name: ""

  # E2-T Instance ID
  #   Description:  The Instance ID of the E2-T component that
  #                 will be used in the bootstrap file.
  #                 The Instance ID must consist of lower case alphanumeric characters
  #                 or '-', start with an alphabetic character, and end with an alphanumeric
  #                 character (e.g. 'my-name',  or 'abc-123', regex used for validation is
  #                 '^[a-z0-9-]+$'). The Instance ID also cannot be longer than 19 characters!
  #
  #   Example:
  # instanceId: "e2-t"
  #
  instanceId: "e2-t"

  redis:
    enabled: true
    hostname: ""
    port: 0

  nats:
    enabled: true
    hostname: ""
    port: 0

drax:
  role: "ric"

nameOverride: ""
fullnameOverride: ""

initImage:
  redis:
    repository: accelleran/acc-generic-img
    tag: "0.8.0"
    pullPolicy: IfNotPresent
  nats:
    repository: accelleran/acc-generic-img
    tag: "0.8.0"
    pullPolicy: IfNotPresent

accelleranLicense:
  enabled: false

e2-t-sctp:
  enabled: true

  nameOverride: "e2-t-sctp"
  fullnameOverride: ""

  containerName: "e2-t-sctp"

  replicaCount: 1

  image:
    repository: accelleran/e2sctpappl
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  accelleranLicense:
    enabled: false

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true

    # runAsUser: 0
    # privileged: true

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    enabled: true
    name: ""
    type: "ClusterIP"
    ports:
      e2-sctp:
        protocol: "SCTP"
        port: 38482
        targetPort: null
        nodePort: null  # 31900


e2-t-ap:
  enabled: true

  nameOverride: "e2-t-ap"
  fullnameOverride: ""

  containerName: "e2-t-ap"

  replicaCount: null

  image:
    repository: accelleran/e2apintfappl
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  accelleranLicense:
    enabled: false

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 0
    # privileged: true

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


e2-t-sm-kpm:
  enabled: true

  nameOverride: "e2-t-sm-kpm"
  fullnameOverride: ""

  containerName: "e2-t-sm-kpm"

  replicaCount: 1

  image:
    repository: accelleran/e2smkpmappl
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  accelleranLicense:
    enabled: false

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 0
    # privileged: true

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

e2-t-sm-rc:
  enabled: true

  nameOverride: "e2-t-sm-rc"
  fullnameOverride: ""

  containerName: "e2-t-sm-rc"

  replicaCount: 1

  image:
    repository: accelleran/e2smrcappl
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  accelleranLicense:
    enabled: false

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 0
    # privileged: true

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


nats:
  enabled: true

  natsBox:
    enabled: false

redis:
  enabled: true

  architecture: standalone
  auth:
    enabled: false
