{{- include
      "accelleran.common.deployment"
      (fromYaml (include "accelleran.cu-up.deployment.args" .))
-}}


{{- define "accelleran.cu-up.deployment.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "cu-up") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

initContainers:
- {{ fromYaml (include "accelleran.common.init.redis" (fromYaml (include "accelleran.cu-up.init.args" .))) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.common.init.nats" (fromYaml (include "accelleran.cu-up.init.args" .))) | toYaml | nindent 2 }}

containers:
- {{ fromYaml (include "accelleran.cu-up.ctrl-up.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-up.netconf.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-up.pm-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-up.res-mgr.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-up.sctp-e1.container" $) | toYaml | nindent 2 }}
{{- end -}}
