apiVersion: v2
name: golang-nkafka
description: The Accelleran dRAX nats-kafka bridge
type: application
version: 1.2.2
appVersion: 1.3.5
dependencies:
  - name: common
    version: 0.2.2
    repository: https://accelleran.github.io/helm-charts-ng/
