apiVersion: v2
name: cu-up
description: Accelleran 5G CU-UP Components
type: application
version: 7.0.0
# renovate: image=accelleran/cuup-netconf
appVersion: "R4.3.12_leffe"
dependencies:
  - name: common
    version: 0.2.2
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.1.10
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 18.19.3
    repository: https://charts.bitnami.com/bitnami/
