apiVersion: v2
name: config-api
description: Backend of the Accelleran Dashboard
type: application
version: 2.0.0
# renovate: image=accelleran/config-api
appVersion: 2.0.1
dependencies:
  - name: common
    version: 0.2.2
    repository: https://accelleran.github.io/helm-charts/
