name: Conventional Commits

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:

  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Lint PR title
        if: ${{ !cancelled() && (github.event_name == 'pull_request') }}
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint commits
        if: ${{ !cancelled() }}
        id: lint_commits
        uses: wagoid/commitlint-github-action@v5

      - name: Add summary
        if: ${{ !cancelled() }}
        uses: actions/github-script@v7
        with:
          script: |
            const isPr = ${{ github.event_name == 'pull_request' }};
            const prTitle = "${{ github.event.pull_request.title }}";
            const lintPrTitleOutcome = "${{ steps.lint_pr_title.outcome }}";
            const lintCommitsOutput = ${{ steps.lint_commits.outputs.results }};

            const icon = {
              pass: ":white_check_mark:",
              fail: ":x:",
              warn: ":warning:",
            };

            let result = "";
            if (lintCommitsOutput.some((item) => item.errors.length !== 0)) {
              result = icon.fail;
            } else if (lintCommitsOutput.some((item) => item.warnings.length !== 0)) {
              result = icon.warn;
            } else {
              result = icon.pass;
            }

            const title = `${result} Conventional Commits`;

            let prDetails = "";
            if (isPr) {
              prDetails = `${
                lintPrTitleOutcome === "success" ? icon.pass : icon.fail
              } PR title (${prTitle})`;
            } else {
              prDetails = "No PR title to lint";
            }

            let details = [];
            for (item of lintCommitsOutput) {
              const commit = item.message;
              const result = item.errors.length !== 0 ? icon.fail : ((item.warnings.length !== 0) ? icon.warn : icon.pass);
              const messages = [...item.errors, ...item.warnings].join(", ");
              const hash = item.hash;
              details = [...details, [result, commit, messages, hash]];
            }

            await core.summary
              .addHeading(title)
              .addHeading(`${prDetails}`, 4)
              .addTable([
                [
                  { data: "Result", header: true },
                  { data: "Commit", header: true },
                  { data: "Messages", header: true },
                  { data: "Hash", header: true },
                ],
                ...details
              ])
              .addLink("More info on conventional commits", "https://www.conventionalcommits.org/en/v1.0.0/")
              .write();
