name: Release Please PR Labels

on:
  pull_request:
    types:
      - closed

jobs:

  label-release-pr:
    name: Label Release PR
    if: "${{ startsWith(github.event.pull_request.title, 'chore: release') }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Remove pending release label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          type: remove
          labels: "release: pending"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add  ${{ github.event.pull_request.merged && 'approved' || 'rejected' }} release label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          type: add
          labels: "release: ${{ github.event.pull_request.merged && 'approved' || 'rejected' }}"
          token: ${{ secrets.GITHUB_TOKEN }}
